name: BERT_GLUE - Workflow
on: [push]

jobs:
  build:
    name: BERT_GLUE - Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Colab Badge Action 
        uses: trsvchn/colab-badge-action@v2
        with:
          check: 'all'
          update: true
          target_branch: master
          target_repository: ankur-98/BERT_GLUE
