name: BERT_GLUE - Workflow
on: [push]

jobs:
  build:
    name: BERT_GLUE - Colab Button Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Colab Badge Action 
        uses: trsvchn/colab-badge-action@v3.1
        with:
          check: 'all'
          update: true
          target_branch: main
          target_repository: ankur-98/BERT_GLUE

      - name: Add/Update badges
        id: badges
        uses: trsvchn/colab-badge-action@v3
        with:
          check: 'all'
          update: true
          target_branch: main
          target_repository: user/user-repo
